/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChecklistItemCard: typeof import('./src/components/travelPlan/ChecklistItemCard.vue')['default']
    ChecklistStatistics: typeof import('./src/components/travelStats/ChecklistStatistics.vue')['default']
    DateTimeRangePicker: typeof import('./src/components/DateTimeRangePicker.vue')['default']
    ExpenseCard: typeof import('./src/components/travelPlan/ExpenseCard.vue')['default']
    ExpensePositionSelect: typeof import('./src/components/map/ExpensePositionSelect.vue')['default']
    ExpenseStatistics: typeof import('./src/components/travelStats/ExpenseStatistics.vue')['default']
    ExpenseTrandCard: typeof import('./src/components/travelStats/ExpenseTrandCard.vue')['default']
    FabButton: typeof import('./src/components/FabButton.vue')['default']
    MapView: typeof import('./src/components/travelStats/MapView.vue')['default']
    PlanCard: typeof import('./src/components/travelPlan/PlanCard.vue')['default']
    PlanPositionSelect: typeof import('./src/components/map/PlanPositionSelect.vue')['default']
    PlanStatistics: typeof import('./src/components/travelStats/PlanStatistics.vue')['default']
    PrioritySelector: typeof import('./src/components/PrioritySelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TravelBasicInfo: typeof import('./src/components/travelStats/TravelBasicInfo.vue')['default']
    TravelTagSelector: typeof import('./src/components/TravelTagSelector.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCol: typeof import('vant/es')['Col']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
